# Generated by Django 6.0.4 on 2026-04-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Condomínio')),
                ('address_street', models.CharField(max_length=255, verbose_name='Rua')),
                ('address_number', models.CharField(max_length=50, verbose_name='Número')),
                ('address_neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(max_length=2, verbose_name='Estado')),
                ('requires_authorization', models.BooleanField(default=False, verbose_name='Exige autorização de acesso')),
                ('authorization_template', models.TextField(blank=True, verbose_name='Modelo de autorização')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
                'ordering': ['name'],
            },
        ),
    ]
