# Generated by Django 6.0.4 on 2026-04-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('periodicity', models.CharField(choices=[('monthly', 'Mensal'), ('once', 'Única')], default='monthly', max_length=20, verbose_name='Periodicidade')),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor base')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Duração em dias')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['-created_at'],
            },
        ),
    ]
