# Generated by Django 6.0.4 on 2026-04-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
