# Generated by Django 6.0.4 on 2026-04-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_plan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='requires_payment',
            field=models.BooleanField(default=True, verbose_name='Necessita Pagamento'),
        ),
    ]
