# Generated by Django 6.0.4 on 2026-04-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_plan_requires_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_gateway', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('stripe', 'Stripe')], default='mercadopago', max_length=20, verbose_name='Gateway de Pagamento Ativo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
