# Generated by Django 6.0.4 on 2026-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='mercadopago_access_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mercado Pago Access Token'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mercadopago_public_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mercado Pago Public Key'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mercadopago_webhook_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mercado Pago Webhook Secret'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Public Key'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Secret Key'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe Webhook Secret'),
        ),
    ]
