# Generated by Django 6.0.4 on 2026-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_systemsetting_mercadopago_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='active_gateway',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='card_gateway',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('stripe', 'Stripe')], default='mercadopago', max_length=20, verbose_name='Gateway para Cartão'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='pix_gateway',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('stripe', 'Stripe')], default='mercadopago', max_length=20, verbose_name='Gateway para PIX'),
        ),
    ]
