# Generated by Django 6.0.4 on 2026-04-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_remove_systemsetting_active_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='is_automated',
            field=models.BooleanField(default=False, verbose_name='Portaria automatizada com VerticeBook?'),
        ),
    ]
