services:
  evolution_db:
    image: postgres:15-alpine
    container_name: evolution_db
    restart: always
    environment:
      POSTGRES_DB: evolution_db
      POSTGRES_USER: evolution_user
      POSTGRES_PASSWORD: evolution_password
    volumes:
      - evolution_db_data:/var/lib/postgresql/data
    networks:
      - evolution_net

  evolution_redis:
    image: redis:7-alpine
    container_name: evolution_redis
    restart: always
    networks:
      - evolution_net

  evolution_api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution_api
    restart: always
    environment:
      - AUTHENTICATION_API_KEY=vbook_secret_key_2026
      - CONSOLE_ENABLED=true
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution_user:evolution_password@evolution_db:5432/evolution_db?sslmode=disable
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DELAY_MESSAGES=true
      - SERVER_URL=https://wa.verticesistemas.tech
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evolution_redis:6379/0
      - WEBSOCKET_ENABLED=true
      - WEBSOCKET_GLOBAL_EVENTS=true
      - QRCODE_LIMIT=100
      - CONFIG_SESSION_PHONE_CLIENT=Desktop
      - CONFIG_SESSION_PHONE_NAME=Windows
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1017564711
    ports:
      - "8010:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution_net
    depends_on:
      - evolution_db
      - evolution_redis

networks:
  evolution_net:
    driver: bridge

volumes:
  evolution_db_data:
  evolution_instances:
