# Generated by Django 6.0.4 on 2026-04-19 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data inicial')),
                ('end_date', models.DateField(verbose_name='Data final')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nome do cliente')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.property', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-start_date'],
            },
        ),
    ]
