# Generated by Django 6.0.4 on 2026-04-19 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertycost_month_propertycost_year'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_instances', to='properties.propertycost', verbose_name='Custo de Referência')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='reservations.reservation', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Custo da Reserva',
                'verbose_name_plural': 'Custos da Reserva',
            },
        ),
    ]
