# Generated by Django 6.0.4 on 2026-04-20 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservationcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guests_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de hóspedes'),
        ),
    ]
