# Generated by Django 6.0.4 on 2026-04-20 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_guests_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkin_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Token de Check-in'),
        ),
    ]
