# Generated by Django 6.0.4 on 2026-04-20 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_checkin_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Check-in'),
        ),
    ]
