# Generated by Django 6.0.4 on 2026-04-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_checkin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='welcome_message_sent',
            field=models.BooleanField(default=False, verbose_name='Boas-vindas enviada'),
        ),
    ]
