# Generated by Django 6.0.4 on 2026-04-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_client_reservation_checkin_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcomplement',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do Carro'),
        ),
        migrations.AddField(
            model_name='clientcomplement',
            name='car_plate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Carro'),
        ),
    ]
