# Generated by Django 6.0.4 on 2026-04-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_clientcomplement_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='authorization_sent',
            field=models.BooleanField(default=False, verbose_name='Autorização Enviada'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='authorization_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio da Autorização'),
        ),
    ]
