# Generated by Django 6.0.4 on 2026-04-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_reservation_authorization_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
    ]
