# Generated by Django 6.0.4 on 2026-04-23 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_propertycost_provider_alter_propertycost_recipient'),
        ('reservations', '0011_alter_companion_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcost',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_costs', to='properties.serviceprovider', verbose_name='Prestador'),
        ),
    ]
