# Generated by Django 6.0.4 on 2026-04-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_reservationcost_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcost',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Realizado em'),
        ),
        migrations.AddField(
            model_name='reservationcost',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Realizado'),
        ),
    ]
