# Generated by Django 6.0.4 on 2026-04-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_reservationcost_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Reserva Cancelada'),
        ),
    ]
