# Generated by Django 6.0.4 on 2026-04-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_reservation_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de check-in'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de check-out'),
        ),
    ]
