# Generated by Django 6.0.4 on 2026-04-24 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_reservation_checkin_time_reservation_checkout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('payment_date', models.DateField(verbose_name='Data do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pagamento da Reserva',
                'verbose_name_plural': 'Pagamentos da Reserva',
                'ordering': ['payment_date'],
            },
        ),
    ]
