# Generated by Django 6.0.4 on 2026-04-30 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_reservationpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_at', models.DateTimeField(auto_now_add=True, verbose_name='Liberado em')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gate_release', to='reservations.reservation', verbose_name='Reserva')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Porteiro/Usuário')),
            ],
            options={
                'verbose_name': 'Liberação de Portaria',
                'verbose_name_plural': 'Liberações de Portaria',
            },
        ),
    ]
