# Generated by Django 6.0.4 on 2026-04-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_gaterelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkout_completed',
            field=models.BooleanField(default=False, verbose_name='Check-out Realizado'),
        ),
    ]
