# Generated by Django 6.0.4 on 2026-04-30 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_reservation_checkout_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaterelease',
            name='release_type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída')], default='entry', max_length=10, verbose_name='Tipo de Liberação'),
        ),
        migrations.AlterField(
            model_name='gaterelease',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_releases', to='reservations.reservation', verbose_name='Reserva'),
        ),
        migrations.AlterUniqueTogether(
            name='gaterelease',
            unique_together={('reservation', 'release_type')},
        ),
    ]
