# Generated by Django 6.0.4 on 2026-06-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_propertychecklist_propertychecklistitem'),
        ('reservations', '0019_gaterelease_release_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='properties.propertychecklist', verbose_name='Deseja selecionar um check list para enviar para a faxineira realizar no ato da faxina? (irá para a faxineira que utiliza o sistema)'),
        ),
    ]
