# Generated by Django 6.0.4 on 2026-04-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(choices=[('pt-br', 'Português'), ('en', 'English')], default='pt-br', max_length=10, verbose_name='Preferência de Idioma'),
        ),
    ]
