# Generated by Django 6.0.4 on 2026-04-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_connected',
            field=models.BooleanField(default=False, verbose_name='WhatsApp Conectado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_instance_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave da Instância WhatsApp'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_instance_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nome da Instância WhatsApp'),
        ),
    ]
