# Generated by Django 6.0.4 on 2026-04-30 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_mobile_theme_preference'),
        ('administration', '0008_condo_is_automated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='condo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='administration.condo', verbose_name='Condomínio'),
        ),
    ]
