# Generated by Django 6.0.4 on 2026-04-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_condo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador do Sistema'), ('manager', 'Gestor de Propriedades'), ('staff', 'Colaborador de Condomínio')], default='manager', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
