# Generated by Django 6.0.4 on 2026-04-19 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da propriedade')),
                ('description', models.TextField(verbose_name='Descrição da propriedade')),
                ('address_street', models.CharField(max_length=255, verbose_name='Rua')),
                ('address_number', models.CharField(max_length=20, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('address_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(max_length=100, verbose_name='Estado')),
                ('acquisition_date', models.DateField(verbose_name='Data da aquisição')),
                ('acquisition_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da aquisição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'ordering': ['-created_at'],
            },
        ),
    ]
