# Generated by Django 6.0.4 on 2026-04-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Foto de Capa'),
        ),
    ]
