# Generated by Django 6.0.4 on 2026-04-19 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do custo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('monthly', 'Mensal'), ('yearly', 'Anual'), ('per_booking', 'Por reserva'), ('one_time', 'Único')], default='monthly', max_length=20, verbose_name='Frequência')),
                ('category', models.CharField(choices=[('fixed', 'Fixo'), ('variable', 'Variável')], default='fixed', max_length=20, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='properties.property', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Custo da Propriedade',
                'verbose_name_plural': 'Custos da Propriedade',
                'ordering': ['name'],
            },
        ),
    ]
