# Generated by Django 6.0.4 on 2026-04-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycost',
            name='amount_type',
            field=models.CharField(choices=[('fixed', 'Valor Fixo (R$)'), ('percentage', 'Percentual (%)')], default='fixed', max_length=20, verbose_name='Tipo de Valor'),
        ),
        migrations.AddField(
            model_name='propertycost',
            name='recipient',
            field=models.CharField(choices=[('none', 'Nenhum / Próprio'), ('platform', 'Plataforma (Booking/Airbnb/etc)'), ('broker', 'Corretor / Terceiro'), ('other', 'Outro')], default='none', max_length=20, verbose_name='Beneficiário / Destinatário'),
        ),
    ]
