# Generated by Django 6.0.4 on 2026-04-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertycost_amount_type_propertycost_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycost',
            name='category',
        ),
    ]
