# Generated by Django 6.0.4 on 2026-04-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_propertycost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycost',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], null=True, verbose_name='Mês'),
        ),
        migrations.AddField(
            model_name='propertycost',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
    ]
