# Generated by Django 6.0.4 on 2026-04-20 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertycost_month_propertycost_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Mês')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('gross_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Bruto')),
                ('costs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custos')),
                ('net_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Líquido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_histories', to='properties.property', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Histórico Financeiro',
                'verbose_name_plural': 'Históricos Financeiros',
                'ordering': ['-year', '-month'],
                'unique_together': {('property', 'month', 'year')},
            },
        ),
    ]
