# Generated by Django 6.0.4 on 2026-04-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_financialhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='condo_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Condomínio'),
        ),
    ]
