# Generated by Django 6.0.4 on 2026-04-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_condo_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='property_signatures/', verbose_name='Assinatura do Proprietário'),
        ),
    ]
