# Generated by Django 6.0.4 on 2026-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reservation_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instruções de Reserva'),
        ),
    ]
