# Generated by Django 6.0.4 on 2026-04-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_reservation_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='authorization_template',
            field=models.TextField(blank=True, null=True, verbose_name='Modelo de Autorização'),
        ),
    ]
