# Generated by Django 6.0.4 on 2026-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_remove_serviceprovider_property_serviceprovider_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='services',
            field=models.ManyToManyField(blank=True, to='properties.service', verbose_name='Serviços Prestados'),
        ),
    ]
