# Generated by Django 6.0.4 on 2026-04-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_remove_serviceprovider_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='providers/', verbose_name='Foto do Prestador'),
        ),
    ]
