# Generated by Django 6.0.4 on 2026-04-23 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_serviceprovider_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycost',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_costs', to='properties.serviceprovider', verbose_name='Prestador Associado'),
        ),
        migrations.AlterField(
            model_name='propertycost',
            name='recipient',
            field=models.CharField(choices=[('none', 'Nenhum / Próprio'), ('platform', 'Plataforma (Booking/Airbnb/etc)'), ('broker', 'Corretor / Terceiro'), ('provider', 'Prestador'), ('other', 'Outro')], default='none', max_length=20, verbose_name='Beneficiário / Destinatário'),
        ),
    ]
