# Generated by Django 6.0.4 on 2026-04-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_propertycost_provider_alter_propertycost_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='theme',
            field=models.CharField(choices=[('dark', 'Escuro'), ('light', 'Claro')], default='dark', max_length=10, verbose_name='Tema'),
        ),
    ]
