# Generated by Django 6.0.4 on 2026-04-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_serviceprovider_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='share_client_phone',
            field=models.BooleanField(default=False, verbose_name='Enviar telefone do cliente para o prestador em caso de serviço'),
        ),
    ]
