# Generated by Django 6.0.4 on 2026-04-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_share_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_checkin_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário padrão de check-in'),
        ),
        migrations.AddField(
            model_name='property',
            name='default_checkout_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário padrão de check-out'),
        ),
    ]
