# Generated by Django 6.0.4 on 2026-04-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_property_default_checkin_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycost',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
    ]
