# Generated by Django 6.0.4 on 2026-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_propertycost_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Cor no Calendário'),
        ),
    ]
