# Generated by Django 6.0.4 on 2026-04-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_property_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Serviço'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
    ]
