# Generated by Django 6.0.4 on 2026-04-24 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('properties', '0022_alter_service_unique_together_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='condo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='administration.condo', verbose_name='Condomínio'),
        ),
    ]
