# Generated by Django 6.0.4 on 2026-04-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_property_condo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
    ]
