# Generated by Django 6.0.4 on 2026-05-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_providerpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Documento')),
                ('document_date', models.DateField(verbose_name='Data do Documento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('file', models.FileField(upload_to='property_documents/', verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Documento da Propriedade',
                'verbose_name_plural': 'Documentos da Propriedade',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
    ]
