# Generated by Django 6.0.4 on 2026-06-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_propertydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortariaCustomProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_portaria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Portaria')),
                ('bloco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bloco')),
                ('nome_proprietario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Proprietário (Portaria)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portaria_custom', to='properties.property', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Customização da Portaria',
                'verbose_name_plural': 'Customizações da Portaria',
            },
        ),
    ]
