# Generated by Django 6.0.4 on 2026-06-08 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_portariacustomproperty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portariacustomproperty',
            name='telefone_proprietario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Proprietário'),
        ),
        migrations.AlterField(
            model_name='property',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da aquisição'),
        ),
        migrations.AlterField(
            model_name='property',
            name='acquisition_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da aquisição'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da propriedade'),
        ),
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
    ]
