# Generated by Django 6.0.4 on 2026-06-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_serviceprovider_condo_alter_serviceprovider_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('brand', models.CharField(max_length=255, verbose_name='Marca')),
                ('model', models.CharField(max_length=255, verbose_name='Modelo')),
                ('dimensions', models.CharField(max_length=255, verbose_name='Dimensões')),
                ('purchase_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local da compra')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data da compra')),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor da compra')),
                ('product_link', models.URLField(blank=True, null=True, verbose_name='Link do produto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='properties.property', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Especificação da Propriedade',
                'verbose_name_plural': 'Especificações da Propriedade',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='PropertySpecificationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_specifications/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.propertyspecification', verbose_name='Especificação')),
            ],
            options={
                'verbose_name': 'Foto da Especificação',
                'verbose_name_plural': 'Fotos da Especificação',
            },
        ),
    ]
