# Generated by Django 6.0.4 on 2026-06-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_propertyspecification_propertyspecificationphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='properties.property', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Checklist da Propriedade',
                'verbose_name_plural': 'Checklists da Propriedade',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='PropertyChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('default_quantity', models.IntegerField(default=1, verbose_name='Quantidade Padrão')),
                ('default_status', models.CharField(choices=[('bad', 'Ruim'), ('regular', 'Regular'), ('good', 'Bom')], default='good', max_length=10, verbose_name='Estado Padrão')),
                ('evaluation_type', models.CharField(choices=[('quantity', 'Apenas Quantidade'), ('quality', 'Apenas Qualidade'), ('both', 'Quantidade e Qualidade')], default='both', max_length=20, verbose_name='Tipo de Avaliação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='properties.propertychecklist', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'ordering': ['description'],
            },
        ),
    ]
