# Generated by Django 6.0.4 on 2026-06-14 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_propertychecklist_propertychecklistitem'),
        ('reservations', '0020_reservation_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='properties.propertychecklist', verbose_name='Checklist')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='reservations.reservation', verbose_name='Reserva')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_responses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resposta do Checklist',
                'verbose_name_plural': 'Respostas dos Checklists',
                'unique_together': {('reservation', 'checklist')},
            },
        ),
        migrations.CreateModel(
            name='PropertyChecklistItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('quality', models.CharField(blank=True, choices=[('bad', 'Ruim'), ('regular', 'Regular'), ('good', 'Bom')], max_length=10, null=True, verbose_name='Estado/Qualidade')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='properties.propertychecklistitem', verbose_name='Item do Checklist')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_responses', to='properties.propertychecklistresponse', verbose_name='Resposta do Checklist')),
            ],
            options={
                'verbose_name': 'Resposta de Item do Checklist',
                'verbose_name_plural': 'Respostas dos Itens do Checklist',
            },
        ),
    ]
