# Generated by Django 6.0.4 on 2026-06-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_propertychecklistresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertychecklistitem',
            name='photo_required',
            field=models.BooleanField(default=False, verbose_name='Registro fotográfico obrigatório?'),
        ),
        migrations.AddField(
            model_name='propertychecklistitemresponse',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_responses/', verbose_name='Foto / Registro Fotográfico'),
        ),
    ]
