# Generated by Django 6.0.4 on 2026-06-14 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_propertychecklistitem_photo_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderNonConformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Relato da Inconformidade')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='non_conformities/', verbose_name='Registro Fotográfico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformities', to='properties.property', verbose_name='Propriedade')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformities', to='properties.serviceprovider', verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Inconformidade do Prestador',
                'verbose_name_plural': 'Inconformidades dos Prestadores',
                'ordering': ['-created_at'],
            },
        ),
    ]
