# Generated by Django 6.0.4 on 2026-06-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_providernonconformity'),
    ]

    operations = [
        migrations.AddField(
            model_name='providernonconformity',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lido / Verificado'),
        ),
    ]
