# Generated by Django 6.0.4 on 2026-06-14 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_providernonconformity_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providernonconformity',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='non_conformities', to='properties.serviceprovider', verbose_name='Prestador'),
        ),
    ]
