# Generated by Django 6.0.4 on 2026-06-14 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_maintenance_specification'),
        ('properties', '0036_alter_providernonconformity_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='providernonconformity',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_conformities', to='maintenance.maintenance', verbose_name='Manutenção Relacionada'),
        ),
    ]
