# Generated by Django 6.0.4 on 2026-04-29 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pergunta')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Resposta')),
                ('current_url', models.CharField(max_length=255, verbose_name='Tela/URL')),
                ('status', models.CharField(choices=[('answered', 'Respondido'), ('unresolved', 'Incapacidade'), ('error', 'Erro do Sistema')], default='answered', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Interação do Chat',
                'verbose_name_plural': 'Interações do Chat',
                'ordering': ['-created_at'],
            },
        ),
    ]
