# Generated by Django 6.0.4 on 2026-04-29 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajuda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_id', models.CharField(max_length=100, verbose_name='ID da Ajuda/Wizard')),
                ('show_again', models.BooleanField(default=True, verbose_name='Mostrar Novamente')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Última Visualização')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de Ajuda',
                'verbose_name_plural': 'Preferências de Ajuda',
                'unique_together': {('user', 'help_id')},
            },
        ),
    ]
