# Generated by Django 6.0.4 on 2026-04-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Orçamento')),
                ('start_date', models.DateField(verbose_name='Previsão Início')),
                ('end_date', models.DateField(verbose_name='Previsão Fim')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='maintenance.maintenance')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['value'],
            },
        ),
    ]
