# Generated by Django 6.0.4 on 2026-04-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancephoto'),
        ('properties', '0024_property_address_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='executor_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Executante'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='executor_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Executante'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='selected_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_for_maintenance', to='maintenance.budget'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.serviceprovider'),
        ),
    ]
