# Generated by Django 6.0.4 on 2026-04-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenance_executor_name_maintenance_executor_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='executor_name',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='executor_phone',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='selected_budget',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='service_provider',
        ),
    ]
