# Generated by Django 6.0.4 on 2026-04-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_remove_maintenance_executor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='execution_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim Execução'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='execution_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início Execução'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='execution_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Final'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prestador Final'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='provider_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Prestador'),
        ),
    ]
