# Generated by Django 6.0.4 on 2026-04-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenance_execution_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('budgeting', 'Orçamento'), ('in_progress', 'Em andamento'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
