# Generated by Django 6.0.4 on 2026-04-28 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_maintenance_status'),
        ('properties', '0024_property_address_neighborhood'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='properties.serviceprovider', verbose_name='Prestador Associado'),
        ),
        migrations.CreateModel(
            name='ProviderEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Nota (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Avaliação')),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='maintenance.maintenance', verbose_name='Manutenção')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='properties.serviceprovider', verbose_name='Prestador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação do Prestador',
                'verbose_name_plural': 'Avaliações dos Prestadores',
            },
        ),
    ]
