# Generated by Django 6.0.4 on 2026-04-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_maintenance_provider_providerevaluation'),
        ('properties', '0024_property_address_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='maintenances', to='properties.service', verbose_name='Categorias de Serviço'),
        ),
    ]
