# Generated by Django 6.0.4 on 2026-04-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_maintenance_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
    ]
