# Generated by Django 6.0.4 on 2026-05-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_maintenance_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerevaluation',
            name='maintenance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='maintenance.maintenance', verbose_name='Manutenção'),
        ),
    ]
