# Generated by Django 6.0.4 on 2026-06-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_alter_providerevaluation_maintenance'),
        ('properties', '0030_propertyspecification_propertyspecificationphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='properties.propertyspecification', verbose_name='Equipamento / Especificação'),
        ),
    ]
