# Generated by Django 6.0.4 on 2026-06-11 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0028_portariacustomproperty_telefone_proprietario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortariaCheckinManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(verbose_name='Data de Check-in')),
                ('checkout_date', models.DateField(verbose_name='Data de Check-out')),
                ('responsible_name', models.CharField(max_length=255, verbose_name='Nome do Responsável')),
                ('responsible_cpf', models.CharField(max_length=14, verbose_name='CPF do Responsável')),
                ('responsible_rg', models.CharField(max_length=20, verbose_name='RG do Responsável')),
                ('car_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do Veículo')),
                ('car_plate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo')),
                ('checkin_completed', models.BooleanField(default=True, verbose_name='Check-in Realizado')),
                ('checkout_completed', models.BooleanField(default=False, verbose_name='Check-out Realizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_checkins', to='properties.property', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Check-in Manual',
                'verbose_name_plural': 'Check-ins Manuais',
                'db_table': 'portaria_checkin_manual',
                'ordering': ['-checkin_date'],
            },
        ),
        migrations.CreateModel(
            name='PortariaCheckinManualGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('document', models.CharField(max_length=50, verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('checkin_manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='admcondominio.portariacheckinmanual', verbose_name='Check-in Manual')),
            ],
            options={
                'verbose_name': 'Hóspede de Check-in Manual',
                'verbose_name_plural': 'Hóspedes de Check-in Manual',
                'db_table': 'portaria_checkin_manual_hospede',
            },
        ),
    ]
