# Generated by Django 6.0.4 on 2026-06-11 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admcondominio', '0001_initial'),
        ('administration', '0008_condo_is_automated'),
        ('properties', '0028_portariacustomproperty_telefone_proprietario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255, verbose_name='Nome do Prestador')),
                ('provider_cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Prestador')),
                ('provider_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Prestador')),
                ('checkin_time', models.DateTimeField(verbose_name='Hora de Entrada')),
                ('checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo do Acesso')),
                ('car_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do Veículo')),
                ('car_plate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_access_logs', to='administration.condo', verbose_name='Condomínio')),
                ('operator_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_entries', to=settings.AUTH_USER_MODEL, verbose_name='Operador de Entrada')),
                ('operator_exit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_exits', to=settings.AUTH_USER_MODEL, verbose_name='Operador de Saída')),
                ('properties', models.ManyToManyField(blank=True, related_name='provider_access_logs', to='properties.property', verbose_name='Unidades Visitadas')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='properties.serviceprovider', verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Acesso de Prestador',
                'verbose_name_plural': 'Acessos de Prestadores',
                'db_table': 'portaria_prestador_acesso',
                'ordering': ['-checkin_time'],
            },
        ),
    ]
