# Generated by Django 6.0.4 on 2026-06-11 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admcondominio', '0002_serviceprovideraccesslog'),
        ('reservations', '0019_gaterelease_release_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortariaCheckinVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('document', models.CharField(max_length=50, verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('checkin_manual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='admcondominio.portariacheckinmanual', verbose_name='Check-in Manual')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='reservations.reservation', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Visitante do Check-in',
                'verbose_name_plural': 'Visitantes do Check-in',
                'db_table': 'portaria_checkin_visitante',
            },
        ),
    ]
