# Generated by Django 6.0.4 on 2026-06-12 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admcondominio', '0003_portariacheckinvisitor'),
        ('administration', '0008_condo_is_automated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Ativo até')),
                ('all_owners', models.BooleanField(default=True, verbose_name='Para todos proprietários')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='administration.condo', verbose_name='Condomínio')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notices', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('target_owners', models.ManyToManyField(blank=True, related_name='received_notices', to=settings.AUTH_USER_MODEL, verbose_name='Proprietários destino')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'db_table': 'portaria_aviso',
                'ordering': ['-created_at'],
            },
        ),
    ]
